import UIKit
import MessageUI

@MainActor
class ExportService: ObservableObject {
    @Published var showMailComposer = false
    @Published var showExportSuccess = false
    @Published var exportMessage = ""
    @Published var showShareSheet = false
    @Published var shareItems: [Any] = []

    // MARK: - Apple Notes Export

    func exportToAppleNotes(meeting: Meeting) {
        guard let analysis = meeting.analysis else { return }

        let noteBody = """
        \(meeting.displayTitle)
        \(meeting.date.formatted(date: .long, time: .shortened))
        Duration: \(meeting.formattedDuration)

        \(analysis.formattedNotes)
        """

        // Use share sheet — user taps "Notes" from the share options
        shareItems = [noteBody]
        showShareSheet = true
    }

    // MARK: - Email Export

    func prepareEmailExport(meeting: Meeting) -> (subject: String, body: String, htmlBody: String)? {
        guard let analysis = meeting.analysis else { return nil }

        let subject = "Meeting Notes: \(meeting.displayTitle)"
        let plainBody = """
        Meeting: \(meeting.displayTitle)
        Date: \(meeting.date.formatted(date: .long, time: .shortened))
        Duration: \(meeting.formattedDuration)

        \(analysis.formattedNotes)
        """

        return (subject: subject, body: plainBody, htmlBody: analysis.htmlNotes)
    }

    // MARK: - Word Document Export (.docx)

    func exportToWord(meeting: Meeting) -> URL? {
        guard let analysis = meeting.analysis else { return nil }

        // Generate a Word-compatible HTML file (.doc format)
        // Word can open HTML files saved as .doc
        let wordHTML = """
        <html xmlns:o="urn:schemas-microsoft-com:office:office"
              xmlns:w="urn:schemas-microsoft-com:office:word"
              xmlns="http://www.w3.org/TR/REC-html40">
        <head>
        <meta charset="utf-8">
        <style>
            body { font-family: Calibri, sans-serif; font-size: 11pt; color: #333; }
            h1 { font-size: 22pt; color: #1a3c6e; border-bottom: 2px solid #1a3c6e; padding-bottom: 6pt; }
            h2 { font-size: 14pt; color: #1a3c6e; margin-top: 18pt; }
            .meta { color: #666; font-size: 10pt; margin-bottom: 12pt; }
            ul, ol { margin-left: 18pt; }
            li { margin-bottom: 4pt; line-height: 1.4; }
            .summary { font-size: 11pt; line-height: 1.6; }
            .footer { margin-top: 24pt; color: #999; font-size: 9pt; border-top: 1pt solid #ddd; padding-top: 6pt; }
        </style>
        </head>
        <body>
        <h1>\(meeting.displayTitle)</h1>
        <div class="meta">
            Date: \(meeting.date.formatted(date: .long, time: .shortened))<br>
            Duration: \(meeting.formattedDuration)
        </div>

        <h2>Summary</h2>
        <div class="summary">\(analysis.summary)</div>

        \(analysis.participants.isEmpty ? "" : """
        <h2>Participants</h2>
        <ul>\(analysis.participants.map { "<li>\($0)</li>" }.joined())</ul>
        """)

        <h2>Key Points</h2>
        <ol>\(analysis.keyPoints.map { "<li>\($0)</li>" }.joined())</ol>

        \(analysis.decisions.isEmpty ? "" : """
        <h2>Decisions Made</h2>
        <ul>\(analysis.decisions.map { "<li>\($0)</li>" }.joined())</ul>
        """)

        <h2>Next Steps</h2>
        <ol>\(analysis.nextSteps.map { "<li>\($0)</li>" }.joined())</ol>

        \(meeting.transcript != nil ? """
        <h2>Full Transcript</h2>
        <div style="font-size: 10pt; color: #555; line-height: 1.5;">
        \(meeting.transcript ?? "")
        </div>
        """ : "")

        <div class="footer">Generated by Bryan's Notes &mdash; \(analysis.generatedAt.formatted())</div>
        </body>
        </html>
        """

        let sanitizedTitle = meeting.displayTitle
            .replacingOccurrences(of: "/", with: "-")
            .replacingOccurrences(of: ":", with: "-")
        let fileName = "\(sanitizedTitle).doc"

        let tempURL = FileManager.default.temporaryDirectory.appendingPathComponent(fileName)

        do {
            try wordHTML.write(to: tempURL, atomically: true, encoding: .utf8)
            return tempURL
        } catch {
            return nil
        }
    }

    // MARK: - Share Sheet

    func shareAsText(meeting: Meeting) {
        guard let analysis = meeting.analysis else { return }

        let text = """
        \(meeting.displayTitle)
        \(meeting.date.formatted(date: .long, time: .shortened))

        \(analysis.formattedNotes)
        """

        shareItems = [text]
        showShareSheet = true
    }

    func shareAsFile(meeting: Meeting) {
        if let wordURL = exportToWord(meeting: meeting) {
            shareItems = [wordURL]
            showShareSheet = true
        }
    }
}
