import Foundation

struct Meeting: Identifiable, Codable {
    let id: UUID
    var title: String
    var date: Date
    var duration: TimeInterval
    var audioFileName: String?
    var transcript: String?
    var analysis: MeetingAnalysis?
    var g2Analysis: G2Analysis?
    var isRecording: Bool = false
    var isTranscribing: Bool = false
    var isAnalyzing: Bool = false

    init(id: UUID = UUID(), title: String = "", date: Date = Date(), duration: TimeInterval = 0) {
        self.id = id
        self.title = title
        self.date = date
        self.duration = duration
    }

    var displayTitle: String {
        title.isEmpty ? "Meeting \(date.formatted(date: .abbreviated, time: .shortened))" : title
    }

    var formattedDuration: String {
        let minutes = Int(duration) / 60
        let seconds = Int(duration) % 60
        return String(format: "%d:%02d", minutes, seconds)
    }
}

struct MeetingAnalysis: Codable {
    let summary: String
    let keyPoints: [String]
    let nextSteps: [String]
    let decisions: [String]
    let participants: [String]
    let generatedAt: Date

    var formattedNotes: String {
        var output = ""

        output += "MEETING SUMMARY\n"
        output += String(repeating: "=", count: 50) + "\n\n"
        output += summary + "\n\n"

        if !participants.isEmpty {
            output += "PARTICIPANTS\n"
            output += String(repeating: "-", count: 30) + "\n"
            for p in participants { output += "  - \(p)\n" }
            output += "\n"
        }

        output += "KEY POINTS\n"
        output += String(repeating: "-", count: 30) + "\n"
        for (i, point) in keyPoints.enumerated() {
            output += "  \(i + 1). \(point)\n"
        }
        output += "\n"

        if !decisions.isEmpty {
            output += "DECISIONS MADE\n"
            output += String(repeating: "-", count: 30) + "\n"
            for d in decisions { output += "  - \(d)\n" }
            output += "\n"
        }

        output += "NEXT STEPS\n"
        output += String(repeating: "-", count: 30) + "\n"
        for (i, step) in nextSteps.enumerated() {
            output += "  \(i + 1). \(step)\n"
        }
        output += "\n"

        output += "Generated: \(generatedAt.formatted())\n"
        return output
    }

    var htmlNotes: String {
        var html = """
        <html>
        <head>
        <style>
            body { font-family: -apple-system, Helvetica Neue, sans-serif; padding: 20px; color: #1a1a1a; }
            h1 { color: #0066cc; border-bottom: 2px solid #0066cc; padding-bottom: 8px; }
            h2 { color: #333; margin-top: 24px; }
            ul, ol { padding-left: 20px; }
            li { margin-bottom: 6px; line-height: 1.5; }
            .summary { font-size: 16px; line-height: 1.6; color: #444; }
            .footer { margin-top: 30px; color: #999; font-size: 12px; border-top: 1px solid #eee; padding-top: 10px; }
        </style>
        </head>
        <body>
        """

        html += "<h1>Meeting Notes</h1>"
        html += "<div class='summary'><p>\(summary)</p></div>"

        if !participants.isEmpty {
            html += "<h2>Participants</h2><ul>"
            for p in participants { html += "<li>\(p)</li>" }
            html += "</ul>"
        }

        html += "<h2>Key Points</h2><ol>"
        for point in keyPoints { html += "<li>\(point)</li>" }
        html += "</ol>"

        if !decisions.isEmpty {
            html += "<h2>Decisions Made</h2><ul>"
            for d in decisions { html += "<li>\(d)</li>" }
            html += "</ul>"
        }

        html += "<h2>Next Steps</h2><ol>"
        for step in nextSteps { html += "<li>\(step)</li>" }
        html += "</ol>"

        html += "<div class='footer'>Generated by Bryan's Notes - \(generatedAt.formatted())</div>"
        html += "</body></html>"

        return html
    }
}
